// <auto-generated />
namespace Cricket_Auction.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedTeamOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedTeamOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "202210210616081_addedTeamOwner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
